### ISSUE TITLE
ASCII Encoding

### ISSUE THREAD

**Issue by VolfDaim** [mattcone/markdown-guide#193]
An error occurs when trying to preview or save an md file in DILLINGER with non-ASCII characters
```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (_http_outgoing.js:529:3)
    at ServerResponse.header (/home/ubuntu/dillinger/node_modules/express/lib/response.js:771:10)
    at fetchMd (/home/ubuntu/dillinger/plugins/core/server.js:43:9)
    at Layer.handle [as handle_request] (/home/ubuntu/dillinger/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/dillinger/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ubuntu/dillinger/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ubuntu/dillinger/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/dillinger/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/ubuntu/dillinger/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/dillinger/node_modules/express/lib/router/index.js:275:10)
```

**Comment by mattcone** [comment]
Hi! This is the repository for the Markdown Guide website, not dillinger.io. You could post this issue in https://github.com/joemccann/dillinger/issues.
